#!/usr/bin/env bash
# This script is for Question 0 of the networking basics project.
The OSI model is a conceptual model that characterizes the communication functions of a telecommunication system without regard to their underlying internal structure and technology
# It provides information about the OSI model.
From the lowest to the highest level


